# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Showroom APN AUTOMATION"
title_separator: "-"
name: &name "Richard APN"
description: &description "Showroom les applications d'APN AUTOMATION"
url: https://academicpages.github.io
baseurl: ""
repository: "academicpages/academicpages.github.io"

# Site Author
author:
  avatar: "/images/profile.png"       # Chemin correct pour ton avatar
  name: "Richard Martinez"
  pronouns: 
  bio: "Assesseur p√©dagogique APN AUTOMATION"
  location: "Nice, Carros"
  employer: "APN AUTOMATION"
  email: "richard.martinez34@gmail.com"
  
  # Academic websites
  googlescholar: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid: "https://orcid.org/ton-orcid-ici"   # Remplace par ton vrai ORCID
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  
  # Repositories / Dev
  github: "academicpages"
  
  # Social media
  twitter: "apnautomation"                  # Remplace par ton vrai username
  bluesky: "https://bsky.app/profile/tonusername"  # Lien complet vers ton profil

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser: 
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: false

# Analytics
analytics:
  provider: "false"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Permalink global
permalink: /:categories/:title/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Compression HTML
compress_html:
  clippings: all
  ignore:
    envs: development
